/// <reference path="../.astro/types.d.ts" />

interface CominaviWorkerEnv {
  COMINAVI_OAUTH_CIRCLEMS_PRODUCTION_ORIGIN: string;
  COMINAVI_OAUTH_CIRCLEMS_PRODUCTION_CLIENT_ID: string;
  COMINAVI_OAUTH_CIRCLEMS_PRODUCTION_CLIENT_SECRET: string;
  COMINAVI_OAUTH_CIRCLEMS_SANDBOX_ORIGIN: string;
  COMINAVI_OAUTH_CIRCLEMS_SANDBOX_CLIENT_ID: string;
  COMINAVI_OAUTH_CIRCLEMS_SANDBOX_CLIENT_SECRET: string;
  COMINAVI_CIRCLEMS_PRODUCTION_API_ORIGIN: string;
  COMINAVI_CIRCLEMS_SANDBOX_API_ORIGIN: string;
  COMINAVI_JWT_SECRET: string;
  COMINAVI_CRAWLER_WEBHOOK_SECRET: string;
  COMINAVI_APNS_KEY_ID: string;
  COMINAVI_APNS_TEAM_ID: string;
  COMINAVI_APNS_PRIVATE_KEY: string;
  COMINAVI_APNS_BUNDLE_IDS: string;
  COMINAVI_GOOGLE_CLIENT_IDS: string;
  COMINAVI_APPLE_CLIENT_IDS: string;
  COMINAVI_APPLE_TEAM_ID: string;
  COMINAVI_APPLE_KEY_ID: string;
  COMINAVI_APPLE_PRIVATE_KEY_P8_BASE64URL: string;
  COMINAVI_INVITE_TOKEN_SECRET: string;
  COMINAVI_PROVIDER_CREDENTIAL_KEY_V1: string;
  COMINAVI_CATALOG_PUBLISH_SECRET: string;
  COMINAVI_CATALOG_SCHEDULED_PUBLISH_SECRET: string;
  COMINAVI_TESTFLIGHT_URL: string;
  COMINAVI_SHARED_PLAN_MUTATIONS_ENABLED: string;
  COMINAVI_CATALOG_DOWNLOAD_ORIGIN?: string;
  COMINAVI_CATALOG_DOWNLOAD_HMAC_SECRET?: string;
  COMINAVI_CATALOG_R2_ACCESS_KEY_ID?: string;
  COMINAVI_CATALOG_R2_SECRET_ACCESS_KEY?: string;
  TWITTERAPI_IO_API_KEY: string;
  COMINAVI_DB: D1Database;
  COMINAVI_FOLLOWING_SNAPSHOTS: KVNamespace;
  COMINAVI_AVATARS: R2Bucket;
  COMINAVI_CATALOGS: R2Bucket;
  COMINAVI_CATALOG_DOWNLOADS?: R2Bucket;
  COMINAVI_PLAN_SYNC: DurableObjectNamespace;
  COMINAVI_INVITE_RATE_LIMITER: RateLimit;
  COMINAVI_PUSH_QUEUE: Queue<
    import("./lib/server/push-queue").PushQueueMessage
  >;
}

interface Env extends CominaviWorkerEnv {}

declare namespace Cloudflare {
  interface Env extends CominaviWorkerEnv {}
}
